"use client"
import { useState, useEffect } from "react"
export default function TeacherPortal(){
const [verified,setVerified]=useState(false)
const [profile,setProfile]=useState({name:"Rahul Sharma",title:"IIT JEE Physics Expert | 10 Yrs | Allen Kota",about:"Ex-IIT Bombay",experience:"Allen Kota 2018-Present | Resonance 2014-18",education:"B.Tech IIT Bombay 2012 | GATE AIR 45"})
useEffect(()=>{setVerified(localStorage.getItem("teacher_verified")==="true")},[])
function save(){localStorage.setItem("teacher_linkedin_full",JSON.stringify(profile));alert("LinkedIn Resume Saved")}
function verify(){const c=prompt("OTP use 123456"); if(c==="123456"){localStorage.setItem("teacher_verified","true");setVerified(true);alert("Verified")}}
return(<div className="max-w-5xl mx-auto p-6"><div className="flex justify-between"><h1 className="text-3xl font-black">Teacher Portal - LinkedIn Resume</h1>{verified?<span className="bg-green-500 text-white px-3 py-1 rounded-full text-xs">Verified</span>:<button onClick={verify} className="bg-black text-white px-4 py-2 rounded-full text-xs">Verify OTP 123456</button>}</div><div className="mt-6 bg-white border-2 border-black rounded-[1.5rem] p-6"><h3 className="font-bold">Digital Resume Like LinkedIn</h3><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} className="w-full border p-3 rounded-xl mt-3" placeholder="Name"/><input value={profile.title} onChange={e=>setProfile({...profile,title:e.target.value})} className="w-full border p-3 rounded-xl mt-2" placeholder="Title"/><textarea value={profile.experience} onChange={e=>setProfile({...profile,experience:e.target.value})} className="w-full border p-3 rounded-xl mt-2 h-20" placeholder="Experience"/><textarea value={profile.education} onChange={e=>setProfile({...profile,education:e.target.value})} className="w-full border p-3 rounded-xl mt-2 h-16" placeholder="Qualification"/><button onClick={save} className="w-full bg-black text-white py-3 rounded-full mt-3 font-bold">Save Resume</button></div></div>)
}
