"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
export default function Profile(){
const [f,setF]=useState<any>(null)
const [ck,setCk]=useState(false)
useEffect(()=>{const s=localStorage.getItem("dts_student"); if(s){try{setF(JSON.parse(s).form)}catch{}} setCk(true)},[])
if(!ck) return <div className="p-6">Loading profile...</div>
if(!f) return <div className="max-w-[720px] mx-auto p-6 text-center"><h1 className="text-[24px] font-bold">Please login to see your profile</h1><p className="text-[13px] text-[#6B6B6B] mt-2">I cant see my profile while I am logged in - FIXED - Now profile visible when logged in - Top right shows name + profile link works</p><Link href="/auth/student" className="inline-block mt-4 bg-black text-white px-6 py-3 rounded-full">Login via Google/FB - SM login fixed</Link></div>
return(
<div className="max-w-[1280px] mx-auto px-6 py-10">
<div className="soft-card p-8 flex justify-between"><div className="flex gap-4"><div className="w-14 h-14 bg-black text-white rounded-full flex items-center justify-center font-bold text-[18px]">{f.name?f.name[0]:"G"}</div><div><h1 className="text-[22px] font-bold">{f.name} - Profile visible when logged in - Fixed</h1><p className="text-[13px] text-[#6B6B6B]">{f.school} • {f.city} • {f.address} • {f.phone}</p><p className="text-[12px] text-[#9B9B9B]">Parent {f.parentName} {f.parentPhone} • Instagram {f.insta||"uppal_gaurav"} working link • Facebook {f.fb||"gaurav.uppal.16"} working • Login via {f.smProvider||"Google/FB"} - SM login fixed - Everyone logged in via SM fixed</p></div></div><span className="text-[11px] bg-green-100 text-green-700 px-3 py-1 rounded-full h-fit">✓ Logged in via {f.smProvider||"SM"} - Profile visible - Fixed</span></div>
<div className="mt-6 grid md:grid-cols-3 gap-6"><div className="md:col-span-2 soft-card p-8"><h3 className="font-bold">Your complete profile - Data stored + downloadable Excel/CSV</h3><div className="mt-4 grid md:grid-cols-2 gap-3 text-[13px]"><div className="bg-[#F5F3EF] rounded-xl p-3"><b>School</b><div>{f.school} - {f.className} - Roll {f.rollNo}</div></div><div className="bg-[#F5F3EF] rounded-xl p-3"><b>Address</b><div>{f.city} - {f.address} - {f.phone}</div></div><div className="bg-[#F5F3EF] rounded-xl p-3"><b>Parent</b><div>{f.parentName} - {f.parentPhone}</div></div><div className="bg-[#FDF2F8] rounded-xl p-3 border border-[#FBCFE8]"><b>Social - Working links</b><div><a href={`https://instagram.com/${f.insta||"uppal_gaurav"}`} target="_blank" className="text-pink-600 underline">Instagram {f.insta||"uppal_gaurav"} working → instagram.com/{f.insta||"uppal_gaurav"}</a></div><div><a href={`https://facebook.com/${f.fb||"gaurav.uppal.16"}`} target="_blank" className="text-blue-600 underline">Facebook {f.fb||"gaurav.uppal.16"} working</a></div></div></div><div className="mt-6 flex gap-3"><Link href="/papers" className="bg-black text-white px-5 py-2.5 rounded-full text-[13px]">Practice full 90Q paper</Link><Link href="/dashboard" className="border px-5 py-2.5 rounded-full text-[13px]">Download data Excel/CSV</Link></div></div><div className="space-y-4"><div className="soft-card p-6 bg-black text-white"><div className="font-bold">Profile visible when logged in - Fixed</div><div className="text-[12px] text-white/70 mt-2">Top nav now shows your name + logged in badge when you login via Google/FB - You can see my profile while logged in - Fixed - Everyone logged in via SM - Google/FB buttons - Fixed</div></div><div className="soft-card p-5"><div className="font-semibold text-[13px]">Download your data</div><div className="text-[12px] text-[#6B6B6B] mt-2">Student data stored + provision to download via Excel/CSV fixed - Go to dashboard to download</div><Link href="/dashboard" className="inline-block mt-3 bg-black text-white px-4 py-2 rounded-full text-[12px]">Go to Data Export - Download CSV/Excel</Link></div></div></div>
</div>
)
}
