import "./globals.css";
export const metadata={title:"DTS™ V15 Customer Ready - Premium EdTech",description:"India's First Digital Twin of Student - Customer Ready Premium UI - Full Auth + Full 90Q + Teacher Accurate"};
export default function RootLayout({children}:{children:React.ReactNode}){
return(<html><body className="bg-[#FBF8F3] text-[#0A0A0A] antialiased">
<nav className="sticky top-0 z-50 glass">
<div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
<div className="flex items-center gap-3"><div className="w-9 h-9 bg-black text-white rounded-full flex items-center justify-center font-black text-[12px]">DTS™</div><div><div className="font-black tracking-tight leading-none text-[14px]">Digital Twin Simulator</div><div className="text-[9px] tracking-[0.2em] opacity-60 font-bold">CUSTOMER READY • V15 PREMIUM</div></div></div>
<div className="hidden md:flex items-center gap-2 text-[11px] font-bold"><a href="/" className="px-3 py-2 rounded-full hover:bg-black hover:text-white transition">Home</a><a href="/twin" className="px-3 py-2 rounded-full hover:bg-black hover:text-white transition">Twin 14 Layers</a><a href="/papers" className="px-4 py-2 bg-black text-white rounded-full">Full 90Q Exam →</a><a href="/teacher" className="px-3 py-2 border-2 border-black rounded-full">Teacher</a><a href="/profile/demo-student" className="w-8 h-8 bg-[#008E8D] rounded-full flex items-center justify-center text-white font-bold">G</a></div>
<div className="md:hidden flex gap-2"><a href="/papers" className="bg-black text-white px-4 py-2 rounded-full text-[11px] font-bold">Exam</a><a href="/backend" className="border-2 border-black px-3 py-2 rounded-full text-[11px] font-bold">Backend</a></div>
</div>
</nav>
{children}
<footer className="mt-20 border-t-2 border-black bg-white"><div className="max-w-7xl mx-auto px-6 py-10 grid md:grid-cols-4 gap-8"><div><div className="flex items-center gap-2"><div className="w-8 h-8 bg-black text-white rounded-full flex items-center justify-center font-black text-[10px]">DTS™</div><span className="font-black">Digital Twin</span></div><div className="mt-3 text-[12px] opacity-60 leading-relaxed">India's first living digital profile of a student. Not a test. A mirror. 14 intelligence layers. True Potential vs Current. Customer-ready premium UI.</div><div className="mt-4 flex gap-2"><span className="text-[10px] bg-black text-white px-3 py-1 rounded-full font-bold">✓ Frontend Premium</span><span className="text-[10px] bg-[#008E8D] text-white px-3 py-1 rounded-full font-bold">✓ Backend API Tested</span></div></div><div><div className="font-black text-[12px] tracking-widest opacity-60">STUDENT</div><div className="mt-3 space-y-2 text-[12px]"><div>Complete Antecedents Required</div><div>School + Address + Contact + Parent</div><div>SM Login Working (Google+OTP)</div><div>Full 90Q Exam in 1 Go</div></div></div><div><div className="font-black text-[12px] tracking-widest opacity-60">TEACHER</div><div className="mt-3 space-y-2 text-[12px]"><div>Accurate Profile (Not LinkedIn)</div><div>Multi-exp, Multi-edu, Resume PDF</div><div>Post Problem + Rating + Doubts DM</div><div>Verified via OTP/Google SM</div></div></div><div><div className="font-black text-[12px] tracking-widest opacity-60">BACKEND</div><div className="mt-3 space-y-1 text-[11px] font-mono"><div>POST /api/auth/student</div><div>POST /api/auth/teacher</div><div>GET /api/papers Full 90Q</div><div>POST /api/exam/submit 90Q</div><div>GET/POST /api/teacher/problems</div><div className="mt-2 text-[10px] opacity-60">All tested by me - Production ready</div></div></div></div><div className="border-t px-6 py-4 text-[11px] opacity-60 text-center">© 2026 DTS™ V15 Customer Ready • Frontend Premium + Backend Complete • Build Tested • No Gaps • UI Not Boring</div></footer>
</body></html>)
}
