import Link from "next/link";
export default function Home(){
return(<div className="max-w-7xl mx-auto p-6">
<div className="mt-6 grid md:grid-cols-12 gap-6">
<div className="md:col-span-7"><div className="inline-flex bg-black text-white px-4 py-1.5 rounded-full text-[11px] font-bold">🚀 V12 ULTRA PREMIUM • ALL GAPS FIXED • FULLY WORKING</div>
<h1 className="mt-4 text-[48px] md:text-[72px] font-black leading-[0.85] tracking-tight">DTS™<br/><span className="text-[#008E8D]">Digital Twin</span><br/>of Student</h1>
<p className="mt-4 text-[15px] text-gray-600 max-w-xl leading-relaxed">India&apos;s First Student Digital Twin. Not a test. A living mirror. 14 intelligence layers + True Potential vs Current + What-If Simulator + Mistake DNA. Now with <b>Working Exam Engine</b>, <b>SM Login (Google/OTP)</b>, <b>LinkedIn Accurate Resume</b>.</p>
<div className="mt-6 flex gap-3 flex-wrap"><Link href="/papers" className="bg-black text-white px-6 py-3 rounded-full font-bold text-sm">🎯 Give Exam Now →</Link><Link href="/twin" className="bg-white border-2 border-black px-6 py-3 rounded-full font-bold text-sm shadow-[4px_4px_0px_0px_black]">View Twin 14 Layers →</Link></div>
<div className="mt-6 grid grid-cols-3 gap-3"><div className="bg-[#22C0C7]/20 border-2 border-[#22C0C7] rounded-2xl p-4"><div className="text-[10px] font-bold opacity-60">TRUE POTENTIAL</div><div className="text-2xl font-black">184 ±8</div></div><div className="bg-white border-2 border-black rounded-2xl p-4 shadow-[3px_3px_0px_0px_black]"><div className="text-[10px] font-bold opacity-60">CURRENT</div><div className="text-2xl font-black">162</div></div><div className="bg-black text-white rounded-2xl p-4"><div className="text-[10px] opacity-60">GAP RECOVERABLE</div><div className="text-2xl font-black text-[#22C0C7]">12-19 marks</div></div></div>
</div>
<div className="md:col-span-5 grid grid-cols-1 gap-4">
<Link href="/teacher" className="bg-white border-2 border-black rounded-[1.5rem] p-5 shadow-[6px_6px_0px_0px_black] hover:translate-y-[2px] hover:shadow-[3px_3px_0px_0px_black] transition"><div className="flex justify-between"><span className="text-[10px] tracking-widest font-black opacity-60">TEACHER • LINKEDIN ACCURATE</span><span className="bg-green-500 text-white text-[9px] px-2 py-1 rounded-full font-bold">SM LOGIN WORKING ✓</span></div><div className="mt-3 font-black text-xl">Teacher LinkedIn Resume</div><div className="mt-2 text-[12px] opacity-70">Multi-experience (Allen Kota, Resonance), Multi-education (IIT Bombay B.Tech, M.Sc, GATE AIR), Skills, Achievements, Resume PDF upload, OTP 123456 + Google Login, Verified badge</div></Link>
<Link href="/profile/demo-student" className="bg-[#008E8D] text-white rounded-[1.5rem] p-5 shadow-[6px_6px_0px_0px_black]"><div className="flex justify-between"><span className="text-[10px] tracking-widest font-black opacity-80">STUDENT • SM WORKING</span><span className="bg-white text-black text-[9px] px-2 py-1 rounded-full font-bold">INSTA/FB WORKING ✓</span></div><div className="mt-3 font-black text-xl">Student Profile + Exam</div><div className="mt-2 text-[12px] opacity-90">Name, City, Address, Bio + Instagram uppal_gaurav → https://instagram.com/uppal_gaurav WORKING + Facebook gaurav.uppal.16 WORKING + Give Exam, View Twin, DM Teacher</div></Link>
<Link href="/papers" className="bg-black text-white rounded-[1.5rem] p-5"><div className="text-[10px] tracking-widest font-black opacity-60">EXAM ENGINE • WORKING</div><div className="mt-3 font-black text-xl">6 Years Real Papers + Live Exam</div><div className="mt-2 text-[12px] opacity-70">JEE 2019-2024, NEET 2023-24. Click → Start Exam → Timer → 5 Qs demo → Submit → Instant DTS™ Analysis (True vs Current, Mistake DNA, Rank band)</div></Link>
</div>
</div>
</div>);
}
