"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
export default function S(){
const router=useRouter()
const [f,setF]=useState({name:"",email:"",phone:"",city:"",address:"",school:"",className:"12th",rollNo:"",parentName:"",parentPhone:"",insta:"",fb:""})
async function go(m:string){
 if(!f.name||!f.phone||!f.school||!f.address||!f.parentName||!f.parentPhone){alert("Please complete name, phone, school, address, parent name, parent phone"); return}
 localStorage.setItem("dts_student",JSON.stringify({form:f,verified:true,completed:true}))
 router.push("/papers")
}
return(<div className="max-w-[720px] mx-auto px-6 py-12"><h1 className="text-[28px] font-bold">Create your profile</h1><p className="text-[13px] text-[#6B6B6B] mt-1">Your school, address and contact help us personalize practice and share progress with parents.</p><div className="mt-8 soft-card p-8 grid md:grid-cols-2 gap-4"><div><label className="text-[11px] font-semibold">Full name *</label><input value={f.name} onChange={e=>setF({...f,name:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">Email *</label><input value={f.email} onChange={e=>setF({...f,email:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">Phone *</label><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">City *</label><input value={f.city} onChange={e=>setF({...f,city:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div className="md:col-span-2"><label className="text-[11px] font-semibold">Full address *</label><input value={f.address} onChange={e=>setF({...f,address:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">School *</label><input value={f.school} onChange={e=>setF({...f,school:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">Roll no *</label><input value={f.rollNo} onChange={e=>setF({...f,rollNo:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">Parent name *</label><input value={f.parentName} onChange={e=>setF({...f,parentName:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div><label className="text-[11px] font-semibold">Parent phone *</label><input value={f.parentPhone} onChange={e=>setF({...f,parentPhone:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div><div className="md:col-span-2"><label className="text-[11px] font-semibold">Instagram (uppal_gaurav) - optional but link works</label><input value={f.insta} onChange={e=>setF({...f,insta:e.target.value})} className="w-full mt-1 border rounded-xl px-3 py-2.5 text-[14px]"/></div></div><div className="mt-6 flex gap-3"><button onClick={()=>go("OTP")} className="flex-1 bg-black text-white py-3 rounded-full font-semibold text-[13px]">Continue with OTP 123456</button><button onClick={()=>go("Google")} className="flex-1 border py-3 rounded-full font-semibold text-[13px]">Continue with Google</button></div></div>)
}
