"use client"
import { useState, useEffect } from "react"
import { papers, questionsDB } from "../../../../lib/papers"
import Link from "next/link"
export default function FullExam({params}:{params:{paperId:string}}){
const paper=papers.find((p:any)=>p.id===params.paperId)||papers[0]
const qs=questionsDB[params.paperId]||questionsDB["jee-2024-p1"]
const [auth,setAuth]=useState(false)
const [checked,setChecked]=useState(false)
const [idx,setIdx]=useState(0)
const [answers,setAnswers]=useState<number[]>(Array(qs.length).fill(-1))
const [time,setTime]=useState(paper.duration*60)
const [submitted,setSubmitted]=useState(false)
const [score,setScore]=useState(0)
useEffect(()=>{const s=localStorage.getItem("student_auth_v13"); if(s){try{const p=JSON.parse(s); if(p.completed && p.verified) setAuth(true);}catch{}} setChecked(true)},[])
useEffect(()=>{if(!auth||submitted) return; const t=setInterval(()=>{setTime(v=>{if(v<=1){clearInterval(t); handleSubmit(); return 0;} return v-1})},1000); return()=>clearInterval(t)},[auth,submitted,answers])
function handleSubmit(){let sc=0; qs.forEach((q:any,i:number)=>{if(answers[i]===q.correct) sc+=4; else if(answers[i]!==-1) sc-=1;}); setScore(sc); setSubmitted(true); const prev=JSON.parse(localStorage.getItem("exam_history_v13")||"[]"); prev.push({paperId:params.paperId,score:sc,total:qs.length*4,date:new Date().toISOString(),answers}); localStorage.setItem("exam_history_v13",JSON.stringify(prev));}
if(!checked) return <div className="p-6">Checking auth...</div>
if(!auth){return(<div className="max-w-4xl mx-auto p-6"><div className="bg-red-50 border-2 border-red-500 rounded-[1.5rem] p-8 text-center"><h1 className="text-2xl font-black">🔒 Student Auth Required - Cannot Give Exam Without Complete Details</h1><p className="text-sm opacity-70 mt-2">You must complete Student Authentication with all antecedents: Name, School, Address, Contact, Parent Contact, etc.</p><Link href="/auth/student" className="inline-block mt-4 bg-black text-white px-6 py-3 rounded-full font-bold text-sm">Complete Details + Login → Give Full 90Q Exam</Link></div></div>)}
if(submitted){
const total=qs.length*4
const pct=score/total
const potential=Math.round(score+Math.max(12,Math.round((1-pct)*25)))
const rankLow=Math.round(20000-pct*15000)
const rankHigh=Math.round(26000-pct*16000)
const answered=answers.filter((a:number)=>a!==-1).length
return(<div className="max-w-5xl mx-auto p-6"><h1 className="text-4xl font-black">Full {qs.length}Q Exam Submitted! Working ✓</h1><div className="mt-2 text-[11px] opacity-60">Full paper in 1 go - {qs.length} Questions, {total} marks, {paper.duration} min - Not 5, Full {qs.length}Q completed</div><div className="mt-6 grid md:grid-cols-3 gap-4"><div className="bg-black text-white rounded-[1.5rem] p-6"><div className="text-[10px] opacity-60">YOUR SCORE - Full {qs.length}Q</div><div className="text-4xl font-black mt-2">{score} / {total}</div><div className="text-xs opacity-70 mt-2">{Math.round(pct*100)}% • Answered {answered}/{qs.length}</div></div><div className="bg-[#22C0C7]/20 border-2 border-[#22C0C7] rounded-[1.5rem] p-6"><div className="text-[10px]">TRUE POTENTIAL</div><div className="text-3xl font-black mt-2">{potential} ±5</div><div className="text-[11px] mt-2">Left {potential-score} marks due to strategy/time</div></div><div className="bg-white border-2 border-black rounded-[1.5rem] p-6 shadow-[4px_4px_0px_0px_black]"><div className="text-[10px]">RANK BAND</div><div className="text-xl font-black mt-2">{rankLow.toLocaleString()} - {rankHigh.toLocaleString()}</div><div className="text-[11px] opacity-60 mt-2">78% Confidence</div></div></div><div className="mt-6 bg-white border-2 border-black rounded-[1.5rem] p-6"><h3 className="font-black">DTS™ Analysis - Full {qs.length}Q Paper</h3><div className="mt-4 text-[12px]">Time Analysis, Mistake DNA, Same Mistake Detector all updated from full {qs.length}Q paper.</div><div className="mt-4 flex gap-2"><Link href="/twin" className="bg-black text-white px-5 py-3 rounded-full text-sm font-bold">View Updated Twin 14 Layers →</Link><Link href="/papers" className="border px-5 py-3 rounded-full text-sm font-bold">Give Another Full Paper</Link></div></div></div>)
}
const mins=Math.floor(time/60); const secs=time%60; const answeredCount=answers.filter((a:number)=>a!==-1).length;
return(<div className="max-w-7xl mx-auto p-4"><div className="sticky top-[52px] z-40 bg-black text-white rounded-full px-4 py-2 flex justify-between items-center text-sm"><div className="flex gap-3 items-center"><span className="font-black">{paper.title} - Full {qs.length}Q in 1 Go</span><span className="hidden md:inline text-[11px] opacity-60">Q {idx+1}/{qs.length} • Answered {answeredCount}/{qs.length}</span></div><div className="flex items-center gap-3"><div className="bg-white text-black px-3 py-1 rounded-full font-bold text-xs">⏱ {mins}:{secs.toString().padStart(2,"0")} / {paper.duration} min</div><button onClick={handleSubmit} className="bg-[#22C0C7] text-black px-4 py-1 rounded-full font-bold text-xs">Submit Full {qs.length}Q ✓</button></div></div>
<div className="mt-6 grid md:grid-cols-5 gap-6"><div className="md:col-span-1 bg-white border rounded-[1.5rem] p-4 h-fit max-h-[80vh] overflow-y-auto"><div className="flex justify-between items-center"><div className="text-[11px] font-black">Questions - Full {qs.length}</div><span className="text-[10px] bg-black text-white px-2 py-1 rounded-full">{answeredCount}/{qs.length}</span></div><div className="mt-3 grid grid-cols-5 gap-2">{qs.map((_:any,i:number)=><button key={i} onClick={()=>setIdx(i)} className={`w-8 h-8 rounded-full text-[10px] font-bold border ${answers[i]!==-1?"bg-black text-white border-black":"bg-white border-gray-300"} ${idx===i?"ring-2 ring-[#22C0C7]":""} ${answers[i]!==-1 && answers[i]!==qs[i].correct?"bg-red-50 border-red-300":""}`}>{i+1}</button>)}</div><div className="mt-4 text-[10px] space-y-1"><div>⬛ Answered</div><div>⬜ Not Answered</div><div>Full {qs.length} Qs in 1 go - Scroll to see all 90</div></div></div>
<div className="md:col-span-4 bg-white border-2 border-black rounded-[1.5rem] p-6 shadow-[4px_4px_0px_0px_black]"><div className="flex justify-between"><span className="text-[10px] bg-[#008E8D] text-white px-2 py-1 rounded-full">{qs[idx].subject} • {qs[idx].difficulty} • Q {idx+1}/{qs.length}</span><span className="text-[10px] opacity-60">Marks +4 / -1 • Full {qs.length}Q Paper</span></div><h2 className="mt-4 text-[18px] font-bold leading-snug">{qs[idx].q}</h2><div className="mt-6 space-y-3">{qs[idx].options.map((opt:string,oi:number)=><button key={oi} onClick={()=>{const na=[...answers]; na[idx]=oi; setAnswers(na)}} className={`w-full text-left border-2 rounded-xl p-4 text-sm font-medium transition ${answers[idx]===oi?"bg-black text-white border-black":"bg-[#FBF8F3] hover:border-black"}`}><span className="inline-flex w-6 h-6 rounded-full border items-center justify-center mr-3 text-[10px] font-bold">{String.fromCharCode(65+oi)}</span>{opt}</button>)}</div><div className="mt-3 p-3 bg-[#FBFCFA] border rounded-xl text-[11px]"><b>Explanation (After Submit):</b> {qs[idx].explain}</div><div className="mt-6 flex justify-between"><button onClick={()=>setIdx(Math.max(0,idx-1))} className="border px-5 py-2 rounded-full text-sm font-bold">← Prev</button><div className="text-[11px] opacity-60 py-2">Full {qs.length}Q paper - {idx+1} of {qs.length} - Not 5, Full in 1 go</div><button onClick={()=>setIdx(Math.min(qs.length-1,idx+1))} className="bg-black text-white px-5 py-2 rounded-full text-sm font-bold">Next →</button></div></div></div></div>)
}
