"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
export default function MyProfile(){
const [f,setF]=useState<any>(null)
const [ck,setCk]=useState(false)
useEffect(()=>{const s=localStorage.getItem("dts_student"); if(s){try{setF(JSON.parse(s).form)}catch{}} setCk(true)},[])
if(!ck) return <div className="p-6 text-[13px]">Loading your profile...</div>
if(!f) return <div className="max-w-[720px] mx-auto px-6 py-16 text-center"><h1 className="text-[24px] font-bold">Please login to see your profile</h1><Link href="/auth/student" className="inline-block mt-4 bg-black text-white px-6 py-3 rounded-full text-[13px]">Login with Google or Facebook</Link></div>
return(
<div className="max-w-[1280px] mx-auto px-6 py-10">
<div className="card p-8 flex justify-between items-start"><div className="flex gap-4"><div className="w-14 h-14 bg-black text-white rounded-full flex items-center justify-center font-bold text-[18px]">{f.name?f.name[0]:"G"}</div><div><h1 className="text-[22px] font-bold">{f.name}</h1><p className="text-[13px] text-[#6B6B6B] mt-1">{f.school} • {f.city} • {f.address}</p><p className="text-[12px] text-[#9B9B9B] mt-1">Parent: {f.parentName} • {f.parentPhone} • Instagram: {f.insta||"uppal_gaurav"} • Facebook: {f.fb||"gaurav.uppal.16"}</p></div></div><span className="text-[11px] bg-[#DCFCE7] text-[#166534] px-3 py-1 rounded-full font-semibold">Logged in via {f.provider||"Google"}</span></div>
<div className="mt-6 grid md:grid-cols-3 gap-6">
<div className="md:col-span-2 card p-8"><h3 className="font-bold">Your details</h3><div className="mt-4 grid md:grid-cols-2 gap-3 text-[13px]"><div className="bg-[#F5F3EF] rounded-xl p-3"><div className="text-[11px] text-[#9B9B9B]">SCHOOL</div><div className="font-semibold mt-1">{f.school} • Class {f.className} • Roll {f.rollNo}</div></div><div className="bg-[#F5F3EF] rounded-xl p-3"><div className="text-[11px] text-[#9B9B9B]">CONTACT</div><div className="font-semibold mt-1">{f.city} • {f.phone}</div><div className="text-[12px] text-[#6B6B6B]">{f.address}</div></div><div className="bg-[#F5F3EF] rounded-xl p-3"><div className="text-[11px] text-[#9B9B9B]">PARENT</div><div className="font-semibold mt-1">{f.parentName}</div><div className="text-[12px] text-[#6B6B6B]">{f.parentPhone} • {f.email}</div></div><div className="bg-[#FDF2F8] border border-[#FBCFE8] rounded-xl p-3"><div className="text-[11px] text-[#9B9B9B]">SOCIAL</div><div className="mt-1"><a href={`https://instagram.com/${f.insta||"uppal_gaurav"}`} target="_blank" className="text-[#DB2777] font-semibold underline text-[12px]">Instagram @{f.insta||"uppal_gaurav"}</a></div><div><a href={`https://facebook.com/${f.fb||"gaurav.uppal.16"}`} target="_blank" className="text-[#2563EB] font-semibold underline text-[12px]">Facebook {f.fb||"gaurav.uppal.16"}</a></div></div></div><div className="mt-6 flex gap-3"><Link href="/papers" className="bg-black text-white px-5 py-2.5 rounded-full text-[13px] font-semibold">Practice full paper</Link><Link href="/dashboard" className="border border-[#E8E6E1] px-5 py-2.5 rounded-full text-[13px] font-semibold">Download data</Link></div></div>
<div className="space-y-4"><div className="card p-6 bg-black text-white border-black"><div className="font-bold text-[14px]">Ready to practice?</div><div className="text-[12px] text-white/70 mt-2">Full 90 questions in one go, 360 marks, 180 minutes. Your twin updates after each paper with detailed analysis.</div><Link href="/papers/jee-2024-p1/exam" className="inline-block mt-4 bg-white text-black px-5 py-2.5 rounded-full text-[12px] font-semibold">Start full paper now</Link></div><div className="card p-5"><div className="font-semibold text-[13px]">Your progress</div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><div className="bg-[#F5F3EF] rounded-full px-3 py-2 flex justify-between"><span>Knowledge</span><b>88</b></div><div className="bg-[#F5F3EF] rounded-full px-3 py-2 flex justify-between"><span>Accuracy</span><b>84</b></div></div></div></div>
</div>
</div>
)
}
